version: '3.9'

services:
  vectara-answer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vectara-answer
    ports:
      - "3000:3000"
    env_file:
      - .env
