[general]
hf_token="...huggingface-token-if-needed..."

[default]
api_key="...vectara-api-key..."

[feynman]
api_key="zqt_UXrBclYURJiAW9MiKT1L60EJC6iaIoWYj_bSJg"

[vectara-docs]
api_key="zqt_UXrBcnI2UXINZkrv4g1tQPhzj02vfdtqYJIDiA"

[vectara-com]
api_key="zqt_UXrBclYURJiAW9MiKT1L60EJC6iaIoWYj_bSJg"
