corpus_id: 184
customer_id: 1526022105

app_title: "Ask Feynman"
search_title: "Ask Feynman"
search_description: "All of Richard Feynman's lectures"

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 10
rerank: false

enable_source_filters: False
source: ""
