corpus_id: 3
customer_id: 1366999410
app_title: "Ask Feynman"
search_title: "Ask Feynman"
search_description: "All of Richard Feynman's Lectures"
enable_source_filters: False
source:
summary_default_language: eng
summary_num_sentences: 3
summary_num_results: 7
