corpus_id: 174
customer_id: 1526022105

app_title: "Ask GSB"
search_title: "Ask GSB"
search_description: "Stanford Graduate school of Business"

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 10
rerank: true

enable_source_filters: False
source: ""
