corpus_id: 1
customer_id: 405606997

search_title: "Ask Paul Graham"
search_description: "Ask about anything related to startups, entrepreneurship, or venture capital."

enable_source_filters: False
source: ""

summary_mode: False
