corpus_id: 210
customer_id: 1526022105

search_title: "Vectara docs search"

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 7

summary_prompt_name: vectara-summary-ext-v1.3.1_lang

enable_source_filters: False
