corpus_id: "178,179,180,181,182"
customer_id: 1526022105

app_title: "AskNews"
app_header_learn_more_link: "https://vectara.com/developers/sample-apps/"
search_description: "Sample news aggregator built using Vectara"
search_logo_src: "images/asknews_logo.png"
search_logo_alt: "AskNews logo"
search_logo_height: "20"

summary_default_language: "en"
summary_num_sentences: 3
summary_num_results: 10
summary_temp: 0.0
rerank: false

enable_source_filters: True
sources: "BBC,NPR,FOX,CNBC,CNN"
